using System.Collections.Generic;

namespace HS2_SexRobotController.Helpers
{
    internal sealed class BoneAnimationDefiner
    {
        //Based on the HSceneFlag: LoopType
        //used for increasing stroking speed only for slow/weak
        // 0:弱ループ
        // 1:強ループ
        // 2:絶頂前ループ
        // 3:中ループ
        // -1:その他
        internal enum LoopType
        {
            OTHER = -1,
            WEAK_LOOP = 0,
            STRONG_LOOP = 1,
            ORGASM_LOOP = 2,
            MEDIUM_LOOP = 3 // not implemented (has not appeared in logs)
        }
        internal enum BodyBone
        {
            FEMALE,
            FEMALE_HEAD,
            FEMALE_THIGHTL,
            FEMALE_THIGHTR,
            FEMALE_HIPS,
            FEMALE_EARL,
            FEMALE_EARR,
            FEMALE_MOUTH,
            FEMALE_MOUTH_UPPER_LIP,
            FEMALE_MOUTH_LOWER_LIP,
            FEMALE_MOUTHL,
            FEMALE_MOUTHR,
            FEMALE_BREAST,
            FEMALE_BREASTL,
            FEMALE_BREASTR,
            FEMALE_HANDL,
            FEMALE_HAND_THUMBL,
            FEMALE_HAND_INDEXL,
            FEMALE_HAND_MIDDLEL,
            FEMALE_HAND_RINGL,
            FEMALE_HAND_LITTLEL,
            FEMALE_HANDR,
            FEMALE_HAND_THUMBR,
            FEMALE_HAND_INDEXR,
            FEMALE_HAND_MIDDLER,
            FEMALE_HAND_RINGR,
            FEMALE_HAND_LITTLER,
            FEMALE_FOOTL,
            FEMALE_FOOTR,
            FEMALE_TOESL,
            FEMALE_TOESR,
            VAGINA,
            VAGINA_ALT1,
            VAGINA_ALT2,
            ANUS,
            FEMALE_LBUTT,
            FEMALE_RBUTT,
            MALE,
            MALE_HIPS,
            MALE_THIGHTL,
            MALE_THIGHTR,
            MALE_HEAD,
            MALE_HANDL,
            MALE_HAND_THUMBL,
            MALE_HAND_INDEXL,
            MALE_HAND_MIDDLEL,
            MALE_HAND_RINGL,
            MALE_HAND_LITTLEL,
            MALE_HANDR,
            MALE_HAND_THUMBR,
            MALE_HAND_INDEXR,
            MALE_HAND_MIDDLER,
            MALE_HAND_RINGR,
            MALE_HAND_LITTLER,
            PENIS,
            PENIS_BASE,
            PENIS_TIP,
            BALLS_L,
            BALLS_R
        }

        internal static readonly Dictionary<BodyBone, string> bodyBoneDictionary = new Dictionary<BodyBone, string> {
            //{bodyBone.FEMALE, "UNKNOWN"},
            {BodyBone.FEMALE_HEAD, "cf_J_Head"},
            {BodyBone.FEMALE_THIGHTL, "f_k_thigh_L"},
            {BodyBone.FEMALE_THIGHTR, "f_k_thigh_R"},
            {BodyBone.FEMALE_HIPS, "cf_J_Hips"},
            {BodyBone.FEMALE_EARL, "N_Earring_L"},
            {BodyBone.FEMALE_EARR, "N_Earring_R"},
            {BodyBone.FEMALE_MOUTH, "cf_J_MouthCavity"},
            {BodyBone.FEMALE_MOUTH_UPPER_LIP, "cf_J_Mouthup"},
            {BodyBone.FEMALE_MOUTH_LOWER_LIP, "cf_J_MouthLow"},
            {BodyBone.FEMALE_MOUTHL, "cf_J_Mouth_L"},
            {BodyBone.FEMALE_MOUTHR, "cf_J_Mouth_R"},
            {BodyBone.FEMALE_BREAST, "cf_J_Mune00"},
            {BodyBone.FEMALE_BREASTL, "cf_J_Mune02_L"},
            {BodyBone.FEMALE_BREASTR, "cf_J_Mune02_R"},
            {BodyBone.FEMALE_HANDL, "N_Hand_L"},
            {BodyBone.FEMALE_HAND_THUMBL, "cf_j_hand_thumb02_L"},
            {BodyBone.FEMALE_HAND_INDEXL, "N_Index_L"},
            {BodyBone.FEMALE_HAND_MIDDLEL, "N_Middle_L"},
            {BodyBone.FEMALE_HAND_RINGL, "N_Ring_L"},
            {BodyBone.FEMALE_HAND_LITTLEL, "cf_j_hand_little02_L"},
            {BodyBone.FEMALE_HANDR, "N_Hand_R"},
            {BodyBone.FEMALE_HAND_THUMBR, "cf_j_hand_thumb02_R"},
            {BodyBone.FEMALE_HAND_INDEXR, "N_Index_R"},
            {BodyBone.FEMALE_HAND_MIDDLER, "N_Middle_R"},
            {BodyBone.FEMALE_HAND_RINGR, "N_Ring_R"},
            {BodyBone.FEMALE_HAND_LITTLER, "cf_j_hand_little02_R"},
            {BodyBone.FEMALE_FOOTL, "N_Foot_L"},
            {BodyBone.FEMALE_FOOTR, "N_Foot_R"},
            {BodyBone.FEMALE_TOESL, "cf_j_toes01_L"},
            {BodyBone.FEMALE_TOESR, "cf_j_toes01_R"},
            {BodyBone.VAGINA, "cf_J_Kokan"},
            {BodyBone.ANUS, "cf_J_Ana"},
            {BodyBone.FEMALE_LBUTT, "k_f_siriL_00"},
            {BodyBone.FEMALE_RBUTT, "k_f_siriR_00"},
            //{bodyBone.MALE, "UNKNOWN"},
            {BodyBone.MALE_HEAD, "cf_J_Head"},
            {BodyBone.MALE_HIPS, "cf_J_Hips"},
            {BodyBone.MALE_THIGHTL, "cf_j_thigh00_L"},
            {BodyBone.MALE_THIGHTR, "cf_j_thigh00_R"},
            {BodyBone.PENIS, "a_n_dan"},
            {BodyBone.PENIS_BASE, "cm_J_dan100_00"},
            {BodyBone.PENIS_TIP, "cm_J_dan109_00"},
            {BodyBone.BALLS_L, "cm_J_dan_f_L"},
            {BodyBone.BALLS_R, "cm_J_dan_f_R"}
        };

        internal enum FemaleTargetType
        {
            VAGINAL,
            ANAL,
            ORAL,
            BREASTS,
            LEFTHAND,
            RIGHTHAND,
            LEFTFOOT,
            RIGHTFOOT,
            BOTH_FEET,
            INTERCRURAL,
            VAGINALSWAP,
            ORALSWAP,
            BREASTSWAP,
            LEFTHANDSWAP,
            RIGHTHANDSWAP,
            INTERCRURALSWAP,
            LEFTFOOTSWAP,
            RIGHTFOOTSWAP
        }

        internal static Dictionary<string, FemaleTargetType> animationFemaleTargetDictionary = new Dictionary<string, FemaleTargetType>
        {
            // Schema: {ANIMATION NAME, FEMALE TARGET(S) TO USE IN REGARD TO MAPPING TO THE MALE'S PENIS TARGET}

            // Honey Select 2 Service HScene Category
            //handjob
            {"Handjob", FemaleTargetType.LEFTHAND},
            {"Tip Caress", FemaleTargetType.RIGHTHAND},
            {"Exhausted Handjob", FemaleTargetType.RIGHTHAND},
            {"Standing Handjob", FemaleTargetType.RIGHTHAND},
            {"Obligatory Handjob", FemaleTargetType.RIGHTHAND},
            {"Sitting Handjob", FemaleTargetType.LEFTHAND},
            {"Desk Handjob", FemaleTargetType.RIGHTHAND},
            {"Behind Handjob", FemaleTargetType.LEFTHAND},
            {"Reach Around", FemaleTargetType.LEFTHAND},
            {"Sleeping Handjob", FemaleTargetType.RIGHTHAND},
            {"Nipple Lick Handjob", FemaleTargetType.RIGHTHAND},
            {"Sitting Parallel HJ", FemaleTargetType.LEFTHAND},
            //blowjob
            {"Blowjob", FemaleTargetType.ORAL},
            {"Exhausted Blowjob", FemaleTargetType.ORAL},
            {"Blowjob (No Hands)", FemaleTargetType.ORAL},
            {"Deepthroat", FemaleTargetType.ORAL},
            {"Restrained Blowjob", FemaleTargetType.ORAL},
            {"Irrumatio", FemaleTargetType.ORAL},
            {"Glory Hole", FemaleTargetType.ORAL},
            {"Forceful BJ", FemaleTargetType.ORAL},
            {"Sitting Blowjob (No Hands)", FemaleTargetType.ORAL},
            {"Wall-Trapped Blowjob", FemaleTargetType.ORAL},
            {"Squatting Blowjob", FemaleTargetType.ORAL},
            {"Sleeping Blowjob", FemaleTargetType.ORAL},
            {"Wall Irrumatio", FemaleTargetType.ORAL},
            {"Sitting Irrumatio", FemaleTargetType.ORAL},
            {"Sofa Blowjob", FemaleTargetType.ORAL},
            {"Bondage Blowjob", FemaleTargetType.ORAL},
            {"Doggy BJ", FemaleTargetType.ORAL},
            //{"Tip Lick (No Hands)", femaleTargetType.ORAL},
            //titjob
            {"Titjob", FemaleTargetType.BREASTS},
            {"Titjob & Lick", FemaleTargetType.BREASTS},
            {"Titjob & Suck", FemaleTargetType.BREASTS},
            {"Sitting Titjob", FemaleTargetType.BREASTS},
            {"On Top Titjob", FemaleTargetType.BREASTS},
            {"Sitting Titjob & Lick", FemaleTargetType.BREASTS},
            {"Standing Titjob", FemaleTargetType.BREASTS},
            {"Standing Titjob & Lick", FemaleTargetType.BREASTS},
            {"Sleeping Titjob", FemaleTargetType.BREASTS},
            
            // Honey Select 2 Insert HScene Category
            //vaginal
            {"Missionary", FemaleTargetType.VAGINAL},
            {"Breast Massage Missionary", FemaleTargetType.VAGINAL},
            {"Legs Up Missionary", FemaleTargetType.VAGINAL},
            {"Bondage Missionary", FemaleTargetType.VAGINAL},
            {"Obligatory Missionary", FemaleTargetType.VAGINAL},
            {"Standing Missionary", FemaleTargetType.VAGINAL},
            {"Reverse Standing Missionary", FemaleTargetType.VAGINAL},
            {"Table Missionary", FemaleTargetType.VAGINAL},
            {"Floating Missionary", FemaleTargetType.VAGINAL},
            {"Missionary Press", FemaleTargetType.VAGINAL},
            {"Doggy", FemaleTargetType.VAGINAL},
            {"Standing Doggy", FemaleTargetType.VAGINAL},
            {"Thrust Up Doggy", FemaleTargetType.VAGINAL},
            {"Standing Wall Doggy", FemaleTargetType.VAGINAL},
            {"Sitting Reverse Doggy", FemaleTargetType.VAGINAL},
            {"Desk Doggy", FemaleTargetType.VAGINAL},
            {"Counter Doggy", FemaleTargetType.VAGINAL},
            {"Staircase Doggy", FemaleTargetType.VAGINAL},
            {"Wall Hole Doggy", FemaleTargetType.VAGINAL},
            {"Bathtub Reverse Doggy", FemaleTargetType.VAGINAL},
            {"J. Toilet Reverse Doggy", FemaleTargetType.VAGINAL},
            {"Toilet Reverse Doggy", FemaleTargetType.VAGINAL},
            {"Floating Doggy", FemaleTargetType.VAGINAL},
            {"Wall Press Doggy", FemaleTargetType.VAGINAL},
            {"Doggy Back", FemaleTargetType.VAGINAL},
            {"Sitting Face-to-Face", FemaleTargetType.VAGINAL},
            {"Cowgirl", FemaleTargetType.VAGINAL},
            {"Breast Massage Cowgirl", FemaleTargetType.VAGINAL},
            {"Reverse Cowgirl", FemaleTargetType.VAGINAL},
            {"Sofa Cowgirl (Reclining)", FemaleTargetType.VAGINAL},
            {"Sofa Side", FemaleTargetType.VAGINAL},
            {"Riding Sex", FemaleTargetType.VAGINAL},
            {"Standing Bondage", FemaleTargetType.VAGINAL},
            {"Standing Tied", FemaleTargetType.VAGINAL},
            {"Standing Squeeze", FemaleTargetType.VAGINAL},
            {"Bath Sex", FemaleTargetType.VAGINAL},
            {"Lotus", FemaleTargetType.VAGINAL},
            {"Hands Tied", FemaleTargetType.VAGINAL},
            {"The Figurehead", FemaleTargetType.VAGINAL},
            {"Side", FemaleTargetType.VAGINAL},
            {"Piledriver", FemaleTargetType.VAGINAL},
            {"Parallel Plank", FemaleTargetType.VAGINAL},
            {"Standing", FemaleTargetType.VAGINAL},
            {"Desk Side", FemaleTargetType.VAGINAL},
            {"Birthing Chair Sex", FemaleTargetType.VAGINAL},
            {"Suspended Sex", FemaleTargetType.VAGINAL},
            {"Prone Bone", FemaleTargetType.VAGINAL},
            {"Sitting R. Cowgirl & Grope", FemaleTargetType.VAGINAL},
            {"Squatting Sex", FemaleTargetType.VAGINAL},
            //anal
            {"Anal Missionary", FemaleTargetType.ANAL},
            {"Anal Doggy", FemaleTargetType.ANAL},
            {"Standing Wall Anal Doggy", FemaleTargetType.ANAL},
            {"Sitting Anal Reverse Doggy", FemaleTargetType.ANAL},
            {"Anal Piledriver", FemaleTargetType.ANAL},

            //intercrucial / footjob
            {"Thighjob", FemaleTargetType.INTERCRURAL},
            {"Bath Footjob", FemaleTargetType.LEFTFOOT},

            // Honey Select Femdom HScene Category
            {"Cowgirl Pussyjob", FemaleTargetType.INTERCRURAL},
            {"HJ + Pussyjob", FemaleTargetType.INTERCRURAL},
            {"Chair Pussyjob", FemaleTargetType.INTERCRURAL},
            {"All-Fours Foreplay", FemaleTargetType.RIGHTHAND},
            {"Femdom Piledriver", FemaleTargetType.VAGINAL},
            {"Piledriver Rimjob", FemaleTargetType.RIGHTHAND},
            {"Stockade Femdom BJ", FemaleTargetType.ORAL},
            {"Stockade Femdom Sex", FemaleTargetType.VAGINAL},
            {"Sitting Bondage", FemaleTargetType.VAGINAL},
            {"Standing Footjob", FemaleTargetType.LEFTFOOT},
            {"Sitting Footjob", FemaleTargetType.LEFTFOOT},
            {"Sitting Bound Footjob", FemaleTargetType.LEFTFOOT},
            {"Domination Reverse Cowgirl", FemaleTargetType.VAGINAL},
            {"Anal Reverse Cowgirl", FemaleTargetType.ANAL},
            {"Sitting side", FemaleTargetType.VAGINAL},
            {"Cunnilingus HJ", FemaleTargetType.LEFTHAND},

            // Honey Select 2 Female Group HScene Category
            {"2x Cowgirl", FemaleTargetType.VAGINAL},
            {"2x Cowgirl (Alt)", FemaleTargetType.VAGINALSWAP},
            {"2x Blowjob", FemaleTargetType.ORAL},
            {"2x Blowjob (Alt)", FemaleTargetType.ORALSWAP},
            {"Thighjob Sandwich", FemaleTargetType.INTERCRURAL},
            {"Thighjob Sandwich (Alt)", FemaleTargetType.INTERCRURALSWAP},
            {"Doggy + Fingering", FemaleTargetType.VAGINAL},
            {"Doggy + Fingering (Alt)", FemaleTargetType.VAGINALSWAP},
            {"2x HJ Lick", FemaleTargetType.RIGHTHANDSWAP},
            {"2x HJ Lick (Alt)", FemaleTargetType.RIGHTHAND},
            {"Sitting Cunnilingus", FemaleTargetType.VAGINAL},
            {"Sitting Cunnilingus (Alt)", FemaleTargetType.VAGINALSWAP},
            {"2x Standing Missionary", FemaleTargetType.VAGINAL},
            {"2x Standing Missionary (alt)", FemaleTargetType.VAGINALSWAP},

            // Honey Select 2 Male Group HScene Category
            {"Double Blowjob", FemaleTargetType.ORAL},
            {"Doggy + BJ", FemaleTargetType.VAGINAL},

            // Honey Select 2 Special HScene Category
            {"69", FemaleTargetType.ORAL}
        };
    }
}
